
import type { Item, ModerationItem } from "@/types";

export const locations = ["Mumbai", "Delhi", "Bangalore", "Kolkata", "Chennai", "Sydney", "Melbourne"];

export const moderationItems: ModerationItem[] = [
    { type: "Business", title: "Mumbai Delights", user: "user@example.com", time: "36m ago", status: "Pending" },
    { type: "Event", title: "Late Night Party", user: "reporter@example.com", time: "2h ago", status: "Reported", reason: "Spam" },
    { type: "Community", title: "Delhi Bikers Group", user: "newuser@example.com", time: "1d ago", status: "Pending" },
    { type: "Deal", title: "Free Coffee", user: "bizowner@example.com", time: "2d ago", status: "Pending" },
    { type: "Business", title: "Sydney Sari Palace", user: "owner@example.com", time: "3d ago", status: "Pending" },
    { type: "Community", title: "Chennai Coders", user: "dev@example.com", time: "4d ago", status: "Approved" },
    { type: "Event", title: "Beach Cleanup", user: "volunteer@example.com", time: "5d ago", status: "Approved" },
    { type: "Deal", title: "Invalid Deal", user: "reporter2@example.com", time: "6d ago", status: "Rejected", reason: "Expired" },
];

export const allItems: Item[] = [
  {
    id: "1",
    slug: "diwali-mela-2024",
    title: "Diwali Mela 2024",
    description: "Celebrate the festival of lights with us. Enjoy food, music, and cultural performances.",
    category: "Event",
    location: "Sydney",
    image: "https://placehold.co/600x400.png",
    date: "2024-11-01",
    price: 1500,
    ticketsAvailable: 500,
    organizer: "Indian Cultural Society",
  },
  {
    id: "2",
    slug: "sydney-indians-group",
    title: "Sydney Indians Group",
    description: "A community for Indians living in Sydney to connect, share, and celebrate.",
    category: "Community",
    location: "Sydney",
    image: "https://placehold.co/600x400.png",
  },
  {
    id: "3",
    slug: "delhi-delights-restaurant",
    title: "Delhi Delights Restaurant",
    description: "Authentic North Indian cuisine. Serving the best butter chicken in town.",
    category: "Business",
    location: "Sydney",
    image: "https://placehold.co/600x400.png",
  },
  {
    id: "4",
    slug: "20-off-thaali",
    title: "20% Off on Thaali",
    description: "Get 20% off on our special lunch thaali. Valid for a limited time only.",
    category: "Deal",
    location: "Sydney",
    image: "https://placehold.co/600x400.png",
    date: "2024-09-30",
  },
  {
    id: "5",
    slug: "lagaan-once-upon-a-time",
    title: "Lagaan: Once Upon a Time in India",
    description: "A classic Bollywood movie screening. A must-watch for all cricket and movie lovers.",
    category: "Movie",
    location: "Sydney",
    image: "https://placehold.co/600x400.png",
    director: "Ashutosh Gowariker",
    cast: ["Aamir Khan", "Gracy Singh"],
    genre: "Drama/Sport",
  },
   {
    id: "6",
    slug: "holi-festival-of-colours",
    title: "Holi - Festival of Colours",
    description: "Join us for a vibrant celebration of Holi with colors, music, and dance.",
    category: "Event",
    location: "Melbourne",
    image: "https://placehold.co/600x400.png",
    date: "2025-03-14",
    price: 2500,
  },
   {
    id: "7",
    slug: "mumbai-spice",
    title: "Mumbai Spice",
    description: "Authentic street food from the heart of Mumbai.",
    category: "Business",
    location: "Melbourne",
    image: "https://placehold.co/600x400.png",
  },
  {
    id: "8",
    slug: "melbourne-indians-community",
    title: "Melbourne Indians Community",
    description: "Connect with fellow Indians in Melbourne. Regular meetups and events.",
    category: "Community",
    location: "Melbourne",
    image: "https://placehold.co/600x400.png",
  },
];
